version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "06:30"
    timezone: Asia/Singapore
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
